apiVersion: v1
kind: Service
metadata:
  name: owntone
  namespace: app-teddycloud
  labels:
    app: owntone
spec:
  selector:
    app: owntone
  type: ClusterIP
  ports:
  - name: http
    port: 3689
    targetPort: http
    protocol: TCP
  - name: websocket
    port: 3688
    targetPort: websocket
    protocol: TCP
