# use automatic discovery of empty disk
kind: LVMCluster
apiVersion: lvm.topolvm.io/v1alpha1
metadata:
  name: my-lvmcluster
  namespace: openshift-lvm-storage
spec:
  storage:
    deviceClasses:
      - default: true
        fstype: xfs
        name: vg1
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
          chunkSizeCalculationPolicy: Static
          metadataSizeCalculationPolicy: Host
