apiVersion: v1
kind: ConfigMap
metadata:
  name: tonie-mappings
  namespace: app-teddycloud
data:
  tonie-mappings.json: |
    {
      "mappings": [
        {
          "tagId": "E00403500EEA4BF2",
          "spotifyUri": "spotify:album:00Pxqrupz6xjkI0vd4Otxb",
          "label": "Die drei ??? - Folge 238: Falsche Schuld"
        },
        {
          "tagId": "E00403500EEA6E4C",
          "spotifyUri": "spotify:album:00Pxqrupz6xjkI0vd4Otxb",
          "label": "Die drei ??? - Folge 238: Falsche Schuld"
        }
      ]
    }
