apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teddycloud-spotify-bridge-spotify
  namespace: app-teddycloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: teddycloud-spotify-bridge-spotify
  data:
  - secretKey: username
    remoteRef:
      key: SPOTIFY_USER
  - secretKey: password
    remoteRef:
      key: SPOTIFY_PASSWORD
