apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teddycloud-proxy-session
  namespace: app-teddycloud
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: teddycloud-proxy-session
  data:
  - secretKey: session_secret
    remoteRef:
      key: OAUTH_PROXY_TEDDYCLOUD_KEY
