apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  devEnvironments:
    defaultEditor: che-incubator/che-code/latest
    secondsOfInactivityBeforeIdling: 3600
    defaultComponents:
    - name: plugin-registry
      pluginRegistry:
        openvsxUrl: https://open-vsx.org
    defaultContainerResources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: '4'
        memory: 4Gi
    storage:
      pvcStrategy: per-workspace
      perWorkspaceStrategyPvcConfig:
        claimSize: 40Gi