apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
  namespace: openshift-devspaces
spec:
  devEnvironments:
    defaultEditor: che-incubator/che-code/latest
    idleTimeoutMinutes: 60
    defaultContainerResources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: '4'
        memory: 4Gi
    storage:
      pvcClaimSize: 40Gi
      pvcStrategy: per-workspace