apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-ssh-key
spec:
  config:
    ignition:
      version: 3.2.0
    passwd:
      users:
      - name: core
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOmQLmq0pGdPNlE3i7nedoBJWYjdLQo5kV8VQ4NjWq2P jweyrich@redhat.com
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMXx32WwufnHiUO0XOB6nw3G5cf4+eLSh8Yvw4eykRQZ Jan bitwarden shared key