apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mealie-creds
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: ZITADEL_MEALIE_CLIENTID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: ZITADEL_MEALIE_CLIENTSECRET
