apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  name: multi-repo
spec:
  started: true
  routingClass: che
  template:
    components:
    - name: universal-developer-image
      container:
        image: registry.redhat.io/devspaces/udi-rhel9@sha256:184f43b31b4bdc7ace01be27f6e57d5bb7cd9203226b5978f084ea0370f2d6f8
        memoryLimit: 32Gi
        memoryRequest: 8Gi
        cpuLimit: "6"
        cpuRequest: "1"
        mountSources: true
        endpoints:
        - name: web-ide
          targetPort: 8080
          exposure: internal
          secure: false
          protocol: http
    plugins:
    - id: che-incubator/che-code/latest
      componentOverrides:
      - name: universal-developer-image
        container:
          endpoints:
          - name: web-ide
            targetPort: 8080
            exposure: internal
            secure: false
            protocol: http
    projects:
    - name: ocp-gitops
      clonePath: crowdsalat/ocp-gitops
      git:
        remotes:
          origin: "https://github.com/CrowdSalat/ocp-gitops.git"
    - name: medi-bucher
      clonePath: crowdsalat/medi-bucher
      git:
        remotes:
          origin: "https://github.com/CrowdSalat/medi-bucher.git"
    - name: teddycloud-spotify-radio-shim
      clonePath: crowdsalat/teddycloud-spotify-radio-shim
      git:
        remotes:
          origin: "https://github.com/CrowdSalat/teddycloud-spotify-radio-shim.git"
    - name: workstation-playbook
      clonePath: crowdsalat/workstation-playbook
      git:
        remotes:
          origin: "https://github.com/CrowdSalat/workstation-playbook.git"
    - name: homelab
      clonePath: crowdsalat/homelab
      git:
        remotes:
          origin: "https://github.com/CrowdSalat/homelab.git"