apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: medi-bucher
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/CrowdSalat/medi-bucher.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: app-medi-bucher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true