apiVersion: v1
kind: ConfigMap
metadata:
  name: couchdb-livesync-config
  namespace: app-obsidian-sync
data:
  99-livesync.ini: |
    [couchdb]
    single_node = true
    max_document_size = 50000000

    [chttpd]
    enable_cors = true
    require_valid_user = true
    max_http_request_size = 4294967296

    [cors]
    credentials = true
    origins = app://obsidian.md, capacitor://localhost, http://localhost
