apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb-creds
  namespace: app-obsidian-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: couchdb-creds
    namespace: app-obsidian-sync
    creationPolicy: Owner
  data:
    - secretKey: COUCHDB_USER
      remoteRef:
        key: COUCHDB_USER
        property: value
    - secretKey: COUCHDB_PASSWORD
      remoteRef:
        key: COUCHDB_PASSWORD
        property: value
