apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: app-obsidian-sync
spec:
  serviceName: couchdb
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      serviceAccountName: couchdb
      containers:
        - name: couchdb
          image: apache/couchdb:3.5.2
          ports:
            - containerPort: 5984
              name: couchdb
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-creds
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-creds
                  key: COUCHDB_PASSWORD
          readinessProbe:
            httpGet:
              path: /_up
              port: 5984
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /opt/couchdb/data
            - name: config
              mountPath: /opt/couchdb/etc/local.d/99-livesync.ini
              subPath: 99-livesync.ini
              readOnly: false
          resources:
            limits:
              memory: 2Gi
              cpu: 1
            requests:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: config
          configMap:
            name: couchdb-livesync-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: lvms-vg1
        resources:
          requests:
            storage: 5Gi
