apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: app-openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: openclaw-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENCLAW_GATEWAY_TOKEN
      remoteRef:
        key: OPENCLAW_GATEWAY_TOKEN
    - secretKey: OPENCLAW_GATEWAY_PASSWORD
      remoteRef:
        key: OPENCLAW_GATEWAY_PASSWORD
