apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-home-pvc
  namespace: app-openclaw
  labels:
    app: openclaw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 10Gi
