apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-creds
  namespace: app-mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: mealie-creds
    creationPolicy: Owner
  data:
    - secretKey: MEALIE_USER
      remoteRef:
        key: MEALIE_USER
    - secretKey: MEALIE_PASSWORD
      remoteRef:
        key: MEALIE_PASSWORD
