apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teddycloud-spotify-shim-config
  namespace: app-teddycloud-spotify-shim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
