kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mealie
  namespace: app-mealie
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
  